-- 1) Create revenue_payments table
CREATE TABLE public.revenue_payments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  revenue_payout_id UUID NOT NULL REFERENCES public.revenue_payouts(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL DEFAULT 0,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.revenue_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rp all own" ON public.revenue_payments
FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE INDEX idx_revenue_payments_payout ON public.revenue_payments(revenue_payout_id);

-- 2) Recompute parent received_amount from payments
CREATE OR REPLACE FUNCTION public.recompute_revenue_received()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE pid uuid;
BEGIN
  pid := COALESCE(NEW.revenue_payout_id, OLD.revenue_payout_id);
  UPDATE public.revenue_payouts
    SET received_amount = COALESCE((SELECT SUM(amount) FROM public.revenue_payments WHERE revenue_payout_id = pid), 0)
  WHERE id = pid;
  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_recompute_revenue_received
AFTER INSERT OR UPDATE OR DELETE ON public.revenue_payments
FOR EACH ROW EXECUTE FUNCTION public.recompute_revenue_received();

-- 3) Sync each payment as a Cash Inflow transaction
CREATE OR REPLACE FUNCTION public.sync_tx_revenue_payment()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    DELETE FROM public.transactions WHERE source_table='revenue_payments' AND source_id = OLD.id;
    RETURN OLD;
  ELSIF TG_OP = 'INSERT' THEN
    INSERT INTO public.transactions(user_id, date, type, category, amount, notes, source_table, source_id)
    VALUES (NEW.user_id, NEW.date, 'Cash Inflow', 'Cash', NEW.amount, NEW.note, 'revenue_payments', NEW.id);
    RETURN NEW;
  ELSE
    UPDATE public.transactions
      SET date = NEW.date, amount = NEW.amount, notes = NEW.note
    WHERE source_table='revenue_payments' AND source_id = NEW.id;
    RETURN NEW;
  END IF;
END;
$$;

CREATE TRIGGER trg_sync_tx_revenue_payment
AFTER INSERT OR UPDATE OR DELETE ON public.revenue_payments
FOR EACH ROW EXECUTE FUNCTION public.sync_tx_revenue_payment();

-- 4) Stop sync_tx_revenue from emitting Cash Inflow rows (now driven by payments).
CREATE OR REPLACE FUNCTION public.sync_tx_revenue()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    DELETE FROM public.transactions WHERE source_table='revenue_payouts' AND source_id = OLD.id;
    RETURN OLD;
  ELSIF TG_OP = 'INSERT' THEN
    INSERT INTO public.transactions(user_id, date, type, category, amount, notes, source_table, source_id)
    VALUES (NEW.user_id, NEW.date, 'Revenue', 'Sales Revenue', NEW.earned_amount, NEW.notes, 'revenue_payouts', NEW.id);
    RETURN NEW;
  ELSE
    UPDATE public.transactions
      SET date = NEW.date, amount = NEW.earned_amount, notes = NEW.notes
    WHERE source_table='revenue_payouts' AND source_id = NEW.id AND type = 'Revenue';
    RETURN NEW;
  END IF;
END;
$$;

-- 5) Backfill: create a payment for every existing payout that has received_amount > 0,
-- then clear duplicate Cash Inflow rows previously generated by sync_tx_revenue.
INSERT INTO public.revenue_payments (user_id, revenue_payout_id, amount, date, note)
SELECT user_id, id, received_amount, date, 'Initial payment'
FROM public.revenue_payouts
WHERE received_amount > 0
  AND NOT EXISTS (SELECT 1 FROM public.revenue_payments rp WHERE rp.revenue_payout_id = revenue_payouts.id);

-- The backfill insert triggers sync_tx_revenue_payment which creates Cash Inflow tx rows
-- linked to revenue_payments. Remove the older Cash Inflow rows linked to revenue_payouts.
DELETE FROM public.transactions WHERE source_table='revenue_payouts' AND type='Cash Inflow';
